name: Publish Releases to Community Add-Ons repository

on:
  release:
    types: [published]

jobs:
  deploy-community-addons:
    runs-on: ubuntu-latest
    steps:
    - name: Publish release to community-addons repository
      if: ${{ !github.event.release.prerelease }}
      run: |
        docker run -it --rm hassioaddons/repository-updater:latest \
          --repository hassio-addons/repository \
          --addon esphome \
          --token "${COMMUNITY_ADDONS_TOKEN}"
      env:
        COMMUNITY_ADDONS_TOKEN: ${{ secrets.COMMUNITY_ADDONS_TOKEN }}

    - name: Publish beta release to community-addons beta repository
      if: ${{ github.event.release.prerelease }}
      run: |
        docker run -it --rm hassioaddons/repository-updater:latest \
          --repository hassio-addons/repository-beta \
          --addon esphome \
          --token "${COMMUNITY_ADDONS_TOKEN}"
      env:
        COMMUNITY_ADDONS_TOKEN: ${{ secrets.COMMUNITY_ADDONS_TOKEN }}
